### ISSUE TITLE
Model conversion problem：optlevel = 0

### ISSUE THREAD

**Issue by manmantang** [pnnx/pnnx#105]
When I export pnnx model with optlevel=0
`opt_model = pnnx.export(model, "output_models/vgg16netvlad.pt", img, optlevel=0)`
The following problems will occur.If set optlevel=2 ,there will be no problem.I don't know why.
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Traceback (most recent call last):
  File "load_openIBL.py", line 35, in <module>
    opt_model = pnnx.export(model, "output_models/vgg16netvlad.pt", img, optlevel=0)
  File "/home/manman/.local/lib/python3.8/site-packages/pnnx/utils/export.py", line 33, in export
    return convert(ptpath, inputs, inputs2, input_shapes, input_types, input_shapes2, input_types2, device, customop, moduleop, optlevel, pnnxparam, pnnxbin, pnnxpy, pnnxonnx, ncnnparam, ncnnbin, ncnnpy)
  File "/home/manman/.local/lib/python3.8/site-packages/pnnx/utils/convert.py", line 166, in convert
    spec.loader.exec_module(foo)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manman/docker_data/python-workspace/py/output_models/vgg16netvlad_pnnx.py", line 94
    v_21 = prim::Constant(value=0.000000)
               ^
SyntaxError: invalid syntax
```

**Comment by manmantang** [comment]
If optlevel=1,different problems will arise
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Traceback (most recent call last):
  File "load_openIBL.py", line 36, in <module>
    output2 = opt_model(img)
  File "/home/manman/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/manman/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/manman/docker_data/python-workspace/py/output_models/vgg16netvlad_pnnx.py", line 197, in forward
    v_265 = v_264.copy(src=v_263, )
AttributeError: 'Tensor' object has no attribute 'copy'
```

**Comment by nihui** [comment]
move to https://github.com/Tencent/ncnn/issues/5247
