### ISSUE TITLE
terminate called after throwing an instance of 'torch::jit::ErrorReport'

### ISSUE THREAD

**Issue by kingzcheung** [pnnx/pnnx#51]
错误如下，没有任何错误信息。
```
pnnxparam = anitnet.pnnx.param
pnnxbin = anitnet.pnnx.bin
pnnxpy = anitnet_pnnx.py
ncnnparam = anitnet.ncnn.param
ncnnbin = anitnet.ncnn.bin
ncnnpy = anitnet_ncnn.py
optlevel = 2
device = cpu
inputshape = [1,3,640,640]f32
inputshape2 = [1,3,320,320]f32
customop = 
moduleop = 
terminate called after throwing an instance of 'torch::jit::ErrorReport'
terminate called recursively
Aborted (core dumped)
```

我使用的pytorch 版本为

```
torch                   1.12.1+cu116
torchmetrics            0.8.2
torchvision             0.13.1+cu116

```

**Comment by csukuangfj** [comment]
你可以用 
```
$ gdb --args pnnx  anitnet.pt
(gdb) run
(gdb) backtrace
```

 然后把 backtrace 贴出来.

**Comment by kingzcheung** [comment]
> 你可以用
> 
> ```
> $ gdb --args pnnx  anitnet.pt
> (gdb) run
> (gdb) backtrace
> ```
> 
> 然后把 backtrace 贴出来.

```
Reading symbols from pnnx...
(No debugging symbols found in pnnx)
(gdb) run
Starting program: /home/ibuddy/bin/pnnx anitnet.pt inputshape=\[1,3,640,640\] inputshape2=\[1,3,320,320\]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
pnnxparam = anitnet.pnnx.param
pnnxbin = anitnet.pnnx.bin
pnnxpy = anitnet_pnnx.py
ncnnparam = anitnet.ncnn.param
ncnnbin = anitnet.ncnn.bin
ncnnpy = anitnet_ncnn.py
optlevel = 2
device = cpu
inputshape = [1,3,640,640]f32
inputshape2 = [1,3,320,320]f32
customop = 
moduleop = 
[New Thread 0x7fffe0c0e700 (LWP 498715)]
[New Thread 0x7fffe040d700 (LWP 498716)]
[New Thread 0x7fffdfc0c700 (LWP 498717)]
[New Thread 0x7fffdf40b700 (LWP 498718)]
[New Thread 0x7fffdec0a700 (LWP 498719)]
[New Thread 0x7fffde409700 (LWP 498720)]
[New Thread 0x7fffddc08700 (LWP 498721)]
[New Thread 0x7fffdd407700 (LWP 498722)]
[New Thread 0x7fffdcc06700 (LWP 498723)]
[New Thread 0x7fffdc405700 (LWP 498724)]
[New Thread 0x7fffdbc04700 (LWP 498725)]
[New Thread 0x7fffdb403700 (LWP 498726)]
[New Thread 0x7fffdac02700 (LWP 498727)]
[New Thread 0x7fffda401700 (LWP 498728)]
[New Thread 0x7fffd9c00700 (LWP 498729)]
[New Thread 0x7fffd93ff700 (LWP 498730)]
[New Thread 0x7fffd8bfe700 (LWP 498731)]
[New Thread 0x7fffd83fd700 (LWP 498732)]
[New Thread 0x7fffd7bfc700 (LWP 498733)]
[New Thread 0x7fffd73fb700 (LWP 498734)]
[New Thread 0x7fffd6bfa700 (LWP 498735)]
[New Thread 0x7fffd63f9700 (LWP 498736)]
[New Thread 0x7fffd5bf8700 (LWP 498737)]
terminate called after throwing an instance of 'torch::jit::ErrorReport'
terminate called recursively

Thread 1 "pnnx" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fffe1527859 in __GI_abort () at abort.c:79
#2  0x00007fffe190d53a in __gnu_cxx::__verbose_terminate_handler() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007fffe190b38c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007fffe190a369 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007fffe190ad21 in __gxx_personality_v0 () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fffe1707bef in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#7  0x00007fffe17085aa in _Unwind_Resume () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#8  0x00007fffe5a01c5e in torch::jit::ConcreteSourceRangeUnpickler::unpickle() () from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#9  0x00007fffe5a03625 in torch::jit::ConcreteSourceRangeUnpickler::findSourceRangeThatGenerated(torch::jit::SourceRange const&) () from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#10 0x00007fffe2ddd78d in torch::jit::SourceRange::highlight(std::ostream&) const () from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#11 0x00007fffe2dc1aa1 in torch::jit::ErrorReport::what() const () from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#12 0x00007fffe18ff8d3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007fffe190b38c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#14 0x00007fffe190b3f7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#15 0x00007fffe190b6a9 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#16 0x00007fffe56fd9d6 in torch::jit::emitBuiltinCall(torch::jit::SourceRange const&, torch::jit::Graph&, c10::Symbol, c10::ArrayRef<torch::jit::NamedValue>, c10::ArrayRef<torch::jit::NamedValue>, c10::optional<torch::jit::NamedValue> const&) () from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#17 0x00007fffe570df45 in torch::jit::BuiltinFunction::call(torch::jit::SourceRange const&, torch::jit::Function&, c10::ArrayRef<torch::jit::NamedValue>, c10::ArrayRef<torch::jit::NamedValue>, unsigned long) () from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#18 0x00007fffe56bc121 in torch::jit::to_ir::emitApplyExpr(torch::jit::Apply&, unsigned long, std::shared_ptr<c10::Type> const&) () from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#19 0x00007fffe56bc9e4 in torch::jit::to_ir::emitSugaredExpr(torch::jit::Expr const&, unsigned long, std::shared_ptr<c10::Type> const&) ()
   from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#20 0x00007fffe56d049f in torch::jit::to_ir::emitSingleAssignment(torch::jit::Assign const&) () from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#21 0x00007fffe56d168d in torch::jit::to_ir::emitAssignment(torch::jit::Assign const&) () from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#22 0x00007fffe56dfd31 in torch::jit::to_ir::emitStatements(torch::jit::ListIterator<torch::jit::Stmt>, torch::jit::ListIterator<torch::jit::Stmt>) ()
   from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#23 0x00007fffe56e5b52 in torch::jit::to_ir::emitDef(torch::jit::Def const&, torch::jit::Self const*, torch::jit::Block*) () from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#24 0x00007fffe5697f07 in torch::jit::CompilationUnit::define(c10::optional<c10::QualifiedName> const&, torch::jit::Def const&, std::shared_ptr<torch::jit::Resolver> const&, torch::jit::Self const*, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, torch::jit::Function*, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, torch::jit::Function*> > > const&, bool, torch::jit::CompilationUnit::FunctionType) const::{lambda(torch::jit::Function&)#1}::operator()(torch::jit::Function&) const [clone .constprop.1989] () from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#25 0x00007fffe562c1bf in torch::jit::GraphFunction::ensure_defined() () from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#26 0x00007fffe5696a31 in torch::jit::CompilationUnit::define(c10::optional<c10::QualifiedName> const&, std::vector<torch::jit::Property, std::allocator<torch::jit::Property> > const&, std::vector<std::shared_ptr<torch::jit::Resolver>, std::allocator<std::shared_ptr<torch::jit::Resolver> > > const&, std::vector<torch::jit::Def, std::allocator<torch::jit::Def> > const&, std::vector<std::shared_ptr<torch::jit::Resolver>, std::allocator<std::shared_ptr<torch::jit::Resolver> > > const&, torch::jit::Self const*, bool) ()
   from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#27 0x00007fffe59de66e in torch::jit::SourceImporterImpl::importClass(c10::QualifiedName const&, torch::jit::ClassDef const&, bool) () from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#28 0x00007fffe59e08eb in torch::jit::SourceImporterImpl::importNamedType(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, torch::jit::ClassDef const&) () from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#29 0x00007fffe59e0d10 in torch::jit::SourceImporterImpl::findNamedType(c10::QualifiedName const&) () from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#30 0x00007fffe59e0d7a in torch::jit::SourceImporterImpl::resolveType(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, torch::jit::SourceRange const&) () from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#31 0x00007fffe5704967 in torch::jit::ScriptTypeParser::parse
#32 0x00007fffe59dee5c in torch::jit::SourceImporterImpl::imp
#33 0x00007fffe59e08eb in torch::jit::SourceImporterImpl::imp
--Type <RET> for more, q to quit, c to continue without pagin
const&) () from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#34 0x00007fffe59e0d10 in torch::jit::SourceImporterImpl::fin
#35 0x00007fffe59e0d7a in torch::jit::SourceImporterImpl::res
onst&) () from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#36 0x00007fffe5704967 in torch::jit::ScriptTypeParser::parse
#37 0x00007fffe59debf5 in torch::jit::SourceImporterImpl::imp
#38 0x00007fffe59e08eb in torch::jit::SourceImporterImpl::imp
const&) () from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#39 0x00007fffe59e0d10 in torch::jit::SourceImporterImpl::fin
#40 0x00007fffe59e0d7a in torch::jit::SourceImporterImpl::res
onst&) () from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#41 0x00007fffe5704967 in torch::jit::ScriptTypeParser::parse
#42 0x00007fffe5704c33 in torch::jit::ScriptTypeParser::parse
   from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#43 0x00007fffe59d59da in torch::jit::SourceImporter::loadTyp
#44 0x00007fffe59cd5fe in std::_Function_handler<c10::StrongT
:basic_string<char, std::char_traits<char>, std::allocator<ch
   from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#45 0x00007fffe5a10eb9 in torch::jit::Unpickler::readGlobal(s
d::char_traits<char>, std::allocator<char> > const&) () from 
#46 0x00007fffe5a13473 in torch::jit::Unpickler::readInstruct
#47 0x00007fffe5a15228 in torch::jit::Unpickler::run() () fro
#48 0x00007fffe5a153ce in torch::jit::Unpickler::parse_ivalue
#49 0x00007fffe59d475d in torch::jit::readArchiveAndTensors(s
d::char_traits<char>, std::allocator<char> > const&, std::__c
ePtr (c10::QualifiedName const&)> >, c10::optional<std::funct
trongTypePtr, c10::IValue)> >, c10::optional<c10::Device>, ca
   from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#50 0x00007fffe59cd92d in torch::jit::(anonymous namespace)::
t&) () from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#51 0x00007fffe59cf28d in torch::jit::(anonymous namespace)::
:char_traits<char>, std::allocator<char> >, std::__cxx11::bas
s<char>, std::allocator<char> > >, std::equal_to<std::__cxx11
<char, std::char_traits<char>, std::allocator<char> > const, 
   from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#52 0x00007fffe59d083d in torch::jit::load(std::shared_ptr<ca
d::char_traits<char>, std::allocator<char> >, std::__cxx11::b
its<char>, std::allocator<char> > >, std::equal_to<std::__cxx
ng<char, std::char_traits<char>, std::allocator<char> > const
   from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#53 0x00007fffe59d29d1 in torch::jit::load(std::__cxx11::basi
__cxx11::basic_string<char, std::char_traits<char>, std::allo
sic_string<char, std::char_traits<char>, std::allocator<char>
:pair<std::__cxx11::basic_string<char, std::char_traits<char>
    () from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
#54 0x00007fffe59d2adf in torch::jit::load(std::__cxx11::basi
   from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
   from /home/ibuddy/bin/pnnx-2022/libtorch_cpu.so
--Type <RET> for more, q to quit, c to continue without paging--
#55 0x0000555555438f81 in main ()



```

**Comment by csukuangfj** [comment]
你的pytorch 咋编译的，用的什么版本？为什么bin下面会有torch 的so？

**Comment by kingzcheung** [comment]
> 你的pytorch 咋编译的，用的什么版本？为什么bin下面会有torch 的so？

这是通过 pip 安装的 pytorch 官方版本 0.12, 我目前切换回0.11之后，可以运行转换

**Comment by csukuangfj** [comment]
解决了就好
